<?php

require __DIR__ . '/../includes.php';

/**
 * Test that the test tools work appropriately
 */
try {
    $pid = start_webserver(TMP_DIR, TMP_DIR);

    if (!$pid) {
        echo "A pid should be generated by start_webserver\n";
        exit(1);
    }

    // Assert that we receive a html document.
    assertCurl('/', '<html>');

    stop_webservers();

    // The webserver is closed properly
    assertCurl("http://127.0.0.1:$pid/ -v",'Connection refused');

} catch (Exception $e) {
    fatalException($e);
}